/* This file is generated by 'makedefs' for reference purposes only. */
/* It is no longer used in the NetHack build. */

#if !defined(CROSSCOMPILE) || !defined(CROSSCOMPILE_TARGET)
#define BUILD_DATE "Wed Sep  9 14:08:13 2026"
#define BUILD_TIME (1788952093UL)

#define VERSION_NUMBER 0x05000000UL
#define VERSION_FEATURES 0x00060040UL
#define IGNORED_FEATURES 0x40080000UL
#define VERSION_SANITY1 0x211e117fUL

#define VERSION_STRING "5.0.0"
#define VERSION_ID \
 "Windows NetHack Version 5.0.0 - last build Wed Sep  9 14:08:13 2026."
#define COPYRIGHT_BANNER_C \
 "         Version 5.0.0 Windows, built Wed Sep  9 14:08:13 2026."
#endif /* !CROSSCOMPILE || !CROSSCOMPILE_TARGET */

